---
title: "ireland_data"
author: "James Joyce"
date: "11/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(ggplot2)
```

```{r}

d <- read_csv("Final/data.csv") 

d1 <- d %>%
    select(iyear, attacktype1_txt, gname) %>%
    filter(gname %in% c("Saor Eire (Irish Republican Group)",
                        "Irish Republican Army (IRA)",
                        "Official Irish Republican Army (OIRA)",
                        "Continuity Irish Republican Army (CIRA)",
                        "Real Irish Republican Army (RIRA)",
                        "The New Irish Republican Army",
                        "Irish National Liberation Army (INLA)",
                        "Irish People's Liberation Organization (IPLO)",
                        "Oglaigh na hEireann",
                        "Dissident Republicans",
                        "Irish Republican Extremists",
                        "Ulster Volunteer Force (UVF)",
                        "Red Hand Commandos",
                        "Red Hand Defenders (RHD)",
                        "Ulster Freedom Fighters (UFF)",
                        "Protestant Action Group",
                        "Loyalist Volunteer Forces (LVF)",
                        "Orange Volunteers (OV)",
                        "South Londonderry Volunteers (SLV)",
                        "Protestant extremists")) %>%
    group_by(iyear, gname, attacktype1_txt) %>%
    summarize(count = n(), .groups= 'drop')

write.csv(d1, "Final/ireland.csv")

```